Repository KTB-19/movie_chatbot, pull requests merged in 2024-09, with the labels that each got.

#18 Feature/ai develop 재질문 처리 및 지역명 수정
  ai/app/api/endpoints/infos.py
  ai/app/api/endpoints/recommends.py
  ai/app/models/info.py
  ai/app/services/KOBIS_영화상영관정보_2024-08-28.xlsx
  ai/app/services/KOBIS_영화상영관정보_2024-08-28.xlsx
  ai/app/services/check_entities.py
  ai/app/services/config.py
  ai/app/services/embeddings.py
  ai/app/services/query_ai_process.py
  ai/app/services/recommend_response.py
  ai/app/services/region_text.txt
  ai/app/services/theater_processing.py
  ai/requirements.txt
  ai/tests/test_codes.py
Labels: ✨ Feature, ✅ Test

#22 날짜 포멧수정
  ai/app/services/query_ai_process.py
Labels: 🐞 BugFix

#19 Feature/connect recommend : Recommend 기능 동작을 위한 추가 수정
  ai/.gitignore
  ai/app/api/dto/recommend_request.py
  ai/app/api/endpoints/recommends.py
  ai/app/services/check_entities.py
  backend/src/main/java/com/ktb19/moviechatbot/constant/Constants.java
  backend/src/main/java/com/ktb19/moviechatbot/controller/MovieController.java
  backend/src/main/java/com/ktb19/moviechatbot/dto/AdditionalParsedQueryResponse.java
  backend/src/main/java/com/ktb19/moviechatbot/dto/AdditionalQueryRequest.java
  backend/src/main/java/com/ktb19/moviechatbot/dto/AiInfosResponse.java
  backend/src/main/java/com/ktb19/moviechatbot/dto/AiRecommendRequest.java
  backend/src/main/java/com/ktb19/moviechatbot/dto/MovieRunningTimesRequest.java
  backend/src/main/java/com/ktb19/moviechatbot/dto/ParsedQueryRequest.java
  backend/src/main/java/com/ktb19/moviechatbot/dto/ParsedQueryResponse.java
  backend/src/main/java/com/ktb19/moviechatbot/dto/QueryDto.java
  backend/src/main/java/com/ktb19/moviechatbot/dto/TheaterRunningTimesDto.java
  backend/src/main/java/com/ktb19/moviechatbot/service/MovieService.java
Labels: ✨ Feature, 🐞 BugFix, 📬 API

#23 Feature/ai develop: 인사 생략 및 엔티티 개수 수정
  ai/app/services/check_entities.py
  ai/app/services/query_ai_process.py
Labels: 🐞 BugFix

#27 fix: 재 응답시 사라지는 문제해결
  ai/app/services/query_ai_process.py
Labels: 🐞 BugFix

#29 Feature/ai develop entities error
  ai/app/services/datetime_format.py
  ai/app/services/query_ai_process.py
Labels: 🐞 BugFix

#31 fix: 리스트,딕셔너리 오류 해결 및 결과값 손실 해결
  ai/app/services/query_ai_process.py
Labels: 🐞 BugFix
