Repository KTB-19/movie_chatbot, pull requests merged in 2024-08, with the labels that each got.

#9 Fix/aiserver url : 운영환경에서 OpenFeign url로 인해 AI Server 연결 안되는 문제 해결
  backend/src/main/java/com/ktb19/moviechatbot/feign/AiServerOpenFeign.java
  backend/src/main/resources/application.yml
  backend/src/test/resources/application.yml
Labels: ⚙ Setting, 🐞 BugFix, 📬 API

#5 Feature/aws terraform
  .gitignore
  cloud/ansible/backend-docker-compose.yml
  cloud/ansible/config.my-cnf
  cloud/ansible/crawling-docker-compose.yml
  cloud/ansible/docker-install.yml
  cloud/ansible/node_exporter.yml
  cloud/ansible/work-instance.yml
  cloud/docker/DevHost/docker-compose.yml
  cloud/docker/backend/backend-docker-compose.yml
  cloud/docker/backend/config.my-cnf
  cloud/docker/mysql/Dockerfile
  cloud/docker/mysql/docker-compose.yml
  cloud/docker/mysql/init.sql
  cloud/terraform/environment/dev/.terraform.lock.hcl
  cloud/terraform/environment/dev/front/.terraform.lock.hcl
  cloud/terraform/environment/dev/front/s3CD.tf
  cloud/terraform/environment/dev/main.tf
  cloud/terraform/environment/dev/output.tf
  cloud/terraform/environment/dev/provider.tf
  cloud/terraform/environment/prod/.terraform.lock.hcl
  cloud/terraform/environment/prod/main.tf
  cloud/terraform/environment/prod/variables.tf
  cloud/terraform/modules/instance/ec2.tf
  cloud/terraform/modules/instance/outputs.tf
  cloud/terraform/modules/instance/variables.tf
  cloud/terraform/modules/vpc/outputs.tf
  cloud/terraform/modules/vpc/variables.tf
  cloud/terraform/modules/vpc/vpc.tf
  crawling/.DS_Store
  crawling/.dockerignore
  crawling/Dockerfile
  crawling/crawler.py
  crawling/process_division.py
  crawling/requirements.txt
Labels: ⚙ Setting, 🌏 Deploy

#15 Feature/aws terraform
  cloud/ansible/docker-install.yml
  cloud/ansible/node_exporter.yml
  cloud/terraform/environment/dev/main.tf
  crawling/main.py
Labels: 🐞 BugFix

#13 Re : Feature/connect ai code : AI 코드 연결
  ai/.gitignore
  ai/Dockerfile
  ai/app/api/dto/additional_infos_request.py
  ai/app/api/endpoints/infos.py
  ai/app/core/config.py
  ai/app/main.py
  ai/app/services/check_entities.py
  ai/app/services/datetime_format.py
  ai/app/services/embeddings.py
  ai/app/services/query_ai_process.py
  ai/app/services/scheduler.py
  ai/app/services/test1.py
  ai/app/services/test2.py
  ai/app/services/vector_store.py
  ai/requirements.txt
  ai/tests/ test_codes.py
  backend/src/main/java/com/ktb19/moviechatbot/ai/QueryAiProcess.py
  backend/src/main/java/com/ktb19/moviechatbot/ai/requirements.txt
  backend/src/main/java/com/ktb19/moviechatbot/ai/test1.py
  backend/src/main/java/com/ktb19/moviechatbot/ai/test2.py
Labels: ✨ Feature, 📬 API
